image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-notification-manager-microservice:
  stage: build
  script:
    gradle notification-manager-microservice:assemble notification-manager-microservice:testClasses

checkStyle-notification-manager-microservice:
  stage: staticAnalysis
  script:
    gradle notification-manager-microservice:checkstyleMain notification-manager-microservice:checkStyleTest
  allow_failure: true

PMD-notification-manager-microservice:
  stage: staticAnalysis
  script:
    gradle notification-manager-microservice:pmdMain
  allow_failure: true

test-notification-manager-microservice:
  stage: test
  script:
    - gradle notification-manager-microservice:test notification-manager-microservice:jacocoTestReport
    - cat notification-manager-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
