image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-gateway:
  stage: build
  script:
    gradle gateway:assemble gateway:testClasses

checkStyle-gateway:
  stage: staticAnalysis
  script:
    gradle gateway:checkstyleMain gateway:checkStyleTest
  allow_failure: true


PMD-gateway:
  stage: staticAnalysis
  script:
    gradle gateway:pmdMain
  allow_failure: true

test-gateway:
  stage: test
  script:
    - gradle gateway:test gateway:jacocoTestReport
    - cat gateway/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
