image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-resource-manager-microservice:
  stage: build
  script:
    gradle resource-manager-microservice:assemble resource-manager-microservice:testClasses

checkStyle-resource-manager-microservice:
  stage: staticAnalysis
  script:
    gradle resource-manager-microservice:checkstyleMain resource-manager-microservice:checkStyleTest
  allow_failure: true

PMD-resource-manager-microservice:
  stage: staticAnalysis
  script:
    gradle resource-manager-microservice:pmdMain
  allow_failure: true

test-resource-manager-microservice:
  stage: test
  script:
    - gradle resource-manager-microservice:test resource-manager-microservice:jacocoTestReport
    - cat resource-manager-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
