image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-kafka-example:
  stage: build
  script:
    gradle kafka-example:assemble kafka-example:testClasses

checkStyle-kafka-example:
  stage: staticAnalysis
  script:
    gradle kafka-example:checkstyleMain kafka-example:checkStyleTest
  allow_failure: true


PMD-kafka-example:
  stage: staticAnalysis
  script:
    gradle kafka-example:pmdMain
  allow_failure: true

test-kafka-example:
  stage: test
  script:
    - gradle kafka-example:test kafka-example:jacocoTestReport
    - cat kafka-example/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
